{{- if .Values.externalsecrets.enabled }}
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ template "app.name" . }}
spec:
  dataFrom:
  - key: {{ .Values.externalsecrets.secretawsname }}
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store
  target:
    creationPolicy: Owner
    name: {{ .Values.externalsecrets.secrettocreate }}
{{- end }}
