{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app.name" . }}
  namespace: {{ template "app.name" . }}
  labels:
    app: {{ template "app.name" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.role_arn }}
{{- end }}
